# Generated by Django 5.0.4 on 2024-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumnail_file',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
