# Generated by Django 5.0.4 on 2024-05-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumnail_file',
            new_name='thumbnail_file',
        ),
    ]
