# Generated by Django 5.0.4 on 2024-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_thumnail_file_video_thumbnail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('animals', 'Animals'), ('landscapes', 'Landscapes')], default='fitness', max_length=10),
        ),
    ]
